name: Fetch OI Wiki Releases

on:
    schedule:
        - cron: "15 9 * * 0"

jobs:
    fetch-releases:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Install Git LFS
              run: |
                  sudo apt-get update
                  sudo apt-get install git-lfs
                  git lfs install
            - name: Configure Git LFS for PDFs
              run: |
                  git lfs track "*.pdf"
                  git add .gitattributes
                  git commit -m "Track PDFs with Git LFS"

            - name: Clear old PDFs
              run: |
                  rm -rf PDFS
                  mkdir PDFS

            - name: Fetch latest releases
              run: |
                  latest_release=$(curl -s https://api.github.com/repos/OI-wiki/OI-Wiki-export/releases | jq -r '.[0].assets[] | select(.name | endswith(".pdf")) | .browser_download_url')
                  second_latest_release=$(curl -s https://api.github.com/repos/OI-wiki/OI-Wiki-export/releases | jq -r '.[1].assets[] | select(.name | endswith(".pdf")) | .browser_download_url')
                  curl -L $latest_release -o PDFS/OI-WIKI_By_Typst.pdf
                  curl -L $second_latest_release -o PDFS/OI-WIKI_By_LaTeX.pdf
            - name: Add and commit PDFs
              run: |
                  git config --global user.name 'github-actions'
                  git config --global user.email 'github-actions@github.com'
                  git add PDFS
                  git commit -m "Update OI Wiki PDFs"
            - name: Push changes
              run: |
                  git push origin main
