name: Fetch OI Wiki Release

on:
    schedule:
        - cron: '25 15 * * *' # Runs every day at 3:04 PM

jobs:
    fetch-release:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Get current date
              run:
                  echo "CURRENT_DATE=$(date +'%Y-%m-%d_%H-%M-%S')" >>
                  $GITHUB_ENV

            - name: Create a new file with current date
              run: touch "${{ github.workspace }}/${{ env.CURRENT_DATE }}"
              env:
                  CURRENT_DATE: ${{ env.CURRENT_DATE }}
