name: Fetch OI Wiki Releases

on:
    push:
        branches:
            - main

jobs:
    fetch-releases:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Install Git LFS
              run: |
                  sudo apt-get update
                  sudo apt-get install git-lfs
                  git lfs install

            - name: Clear old PDFs
              run: |
                  rm -rf PDFS
                  mkdir PDFS

            - name: Fetch latest releases
              run: |
                  latest_release=$(curl -s https://api.github.com/repos/OI-wiki/OI-Wiki-export/releases/latest)
                  second_latest_release=$(curl -s https://api.github.com/repos/OI-wiki/OI-Wiki-export/releases | jq -r '.[1]')

                  latest_pdf_url=$(echo $latest_release | jq -r '.assets[] | select(.name | endswith(".pdf")) | .browser_download_url')
                  second_latest_pdf_url=$(echo $second_latest_release | jq -r '.assets[] | select(.name | endswith(".pdf")) | .browser_download_url')

                  curl -L $latest_pdf_url -o PDFS/OI-WIKI\(By Typst\).pdf
                  curl -L $second_latest_pdf_url -o PDFS/OI-WIKI\(By LaTeX\).pdf
            - name: Add and commit PDFs
              run: |
                  git config --global user.name 'github-actions'
                  git config --global user.email 'github-actions@github.com'
                  git add PDFS
                  git commit -m "Update OI Wiki PDFs"
            - name: Push changes
              run: |
                  git push origin main
