name: Fetch OI Wiki Releases

on:
    schedule:
        - cron: "32 8 * * *" # Runs at 16:40 Beijing time (UTC+8)

jobs:
    fetch-releases:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Install Git LFS
              run: |
                  sudo apt-get update
                  sudo apt-get install git-lfs
                  git lfs install

            - name: Clear old PDFs
              run: |
                  rm -rf PDFS
                  mkdir PDFS

            - name: Fetch latest releases
              run: |
                  latest_release=$(curl -s https://api.github.com/repos/OI-wiki/OI-Wiki-export/releases | jq -r '.[0].assets[] | select(.name | endswith(".pdf")) | .browser_download_url')
                  second_latest_release=$(curl -s https://api.github.com/repos/OI-wiki/OI-Wiki-export/releases | jq -r '.[1].assets[] | select(.name | endswith(".pdf")) | .browser_download_url')
                  curl -L $latest_release -o PDFS/latest_release.pdf
                  curl -L $second_latest_release -o PDFS/second_latest_release.pdf

            - name: Add and commit PDFs
              run: |
                  git add PDFS
                  git commit -m "Update OI Wiki PDFs"

            - name: Push changes
              uses: ad-m/github-push-action@v0.6.0
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
